name: Methodology Proposal
description: Suggest a change to scoring or normalization
title: "[Methodology]: "
labels:
  - methodology
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the proposed methodology change.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this change needed?
    validations:
      required: true

  - type: textarea
    id: proposed_change
    attributes:
      label: Proposed change
      description: Provide details on how scoring or normalization should change.
    validations:
      required: true

  - type: textarea
    id: expected_impact
    attributes:
      label: Expected impact
      description: Describe expected impact on results and interpretation.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe alternatives and why they were not chosen.
